### ISSUE TITLE
SerialPort Native Lib worked in Angular-Electron v2.7.1

### ISSUE THREAD

**Issue by jpiwek** [maximegris/angular-electron#160]
Hi,

I got SerialPort native lib working in Angular-Electron version 2.7.1.
In that case I rebuild the lib and added a line in the webpack.config. Now in version 3.1.0 it doesn't work either....? How to fix it in ???

**Comment by maximegris** [comment]
What does "doesn't work" means ? (npm install error ? compilation error ? npm script error ?)

**Comment by Ronalses** [comment]
@jpiwek I explain here how to solve it https://github.com/maximegris/angular-electron/issues/384#issuecomment-535122273
